# Generated by Django 4.0.1 on 2023-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('points', models.CharField(max_length=100)),
                ('matp', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('place', models.IntegerField()),
            ],
        ),
    ]
