# Generated by Django 4.0.1 on 2023-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eleva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_ea', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_ea', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_ea', models.IntegerField(verbose_name='Matches Played')),
                ('gold_ea', models.IntegerField(verbose_name='Goals Difference')),
                ('place_ea', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Eleven A',
                'verbose_name_plural': 'Eleven A',
            },
        ),
        migrations.CreateModel(
            name='elevb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_eb', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_eb', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_eb', models.IntegerField(verbose_name='Matches Played')),
                ('gold_eb', models.IntegerField(verbose_name='Goals Difference')),
                ('place_eb', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Eleven B',
                'verbose_name_plural': 'Eleven B',
            },
        ),
        migrations.CreateModel(
            name='nina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_na', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_na', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_na', models.IntegerField(verbose_name='Matches Played')),
                ('gold_na', models.IntegerField(verbose_name='Goals Difference')),
                ('place_na', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Nine A',
                'verbose_name_plural': 'Nine A',
            },
        ),
        migrations.CreateModel(
            name='ninb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_nb', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_nb', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_nb', models.IntegerField(verbose_name='Matches Played')),
                ('gold_nb', models.IntegerField(verbose_name='Goals Difference')),
                ('place_nb', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Nine B',
                'verbose_name_plural': 'Nine B',
            },
        ),
        migrations.CreateModel(
            name='sevb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_sb', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_sb', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_sb', models.IntegerField(verbose_name='Matches Played')),
                ('gold_sb', models.IntegerField(verbose_name='Goals Difference')),
                ('place_sb', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Seven B',
                'verbose_name_plural': 'Seven B',
            },
        ),
        migrations.CreateModel(
            name='tena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_ta', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_ta', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_ta', models.IntegerField(verbose_name='Matches Played')),
                ('gold_ta', models.IntegerField(verbose_name='Goals Difference')),
                ('place_ta', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Ten A',
                'verbose_name_plural': 'Ten A',
            },
        ),
        migrations.CreateModel(
            name='tenb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_tb', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_tb', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_tb', models.IntegerField(verbose_name='Matches Played')),
                ('gold_tb', models.IntegerField(verbose_name='Goals Difference')),
                ('place_tb', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Ten B',
                'verbose_name_plural': 'Ten B',
            },
        ),
        migrations.DeleteModel(
            name='seva',
        ),
    ]
