# Generated by Django 4.0.1 on 2023-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eleva_elevb_nina_ninb_sevb_tena_tenb_delete_seva'),
    ]

    operations = [
        migrations.CreateModel(
            name='seva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_sa', models.CharField(max_length=20, verbose_name='Grade')),
                ('points_sa', models.CharField(max_length=100, verbose_name='Points')),
                ('matp_sa', models.IntegerField(verbose_name='Matches Played')),
                ('goldd_sa', models.IntegerField(verbose_name='Goals Difference')),
                ('place_sa', models.IntegerField(verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Seven A',
                'verbose_name_plural': 'Seven A',
            },
        ),
        migrations.RenameField(
            model_name='eleva',
            old_name='gold_ea',
            new_name='goldd_ea',
        ),
        migrations.RenameField(
            model_name='elevb',
            old_name='gold_eb',
            new_name='goldd_eb',
        ),
        migrations.RenameField(
            model_name='nina',
            old_name='gold_na',
            new_name='goldd_na',
        ),
        migrations.RenameField(
            model_name='ninb',
            old_name='gold_nb',
            new_name='goldd_nb',
        ),
        migrations.RenameField(
            model_name='sevb',
            old_name='gold_sb',
            new_name='goldd_sb',
        ),
        migrations.RenameField(
            model_name='tena',
            old_name='gold_ta',
            new_name='goldd_ta',
        ),
        migrations.RenameField(
            model_name='tenb',
            old_name='gold_tb',
            new_name='goldd_tb',
        ),
    ]
