# Generated by Django 4.0.1 on 2023-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seva_rename_gold_ea_eleva_goldd_ea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(verbose_name='Place')),
                ('grade', models.CharField(max_length=10, verbose_name='Grade')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('mtpl', models.IntegerField(verbose_name='Matches Played')),
                ('gldf', models.IntegerField(verbose_name='Goals Difference')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Table',
            },
        ),
    ]
